# Generated by Django 6.0.5 on 2026-06-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Other', 'Other')], default='Other', max_length=50)),
                ('move_type', models.CharField(choices=[('IN', 'in'), ('OUT', 'out')], default='IN', max_length=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'move_type', 'created_at'], name='inventory_s_product_2ce101_idx')],
            },
        ),
    ]
