# Generated by Django 6.0.5 on 2026-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='move_type',
            field=models.CharField(choices=[('IN', 'in'), ('OUT', 'out')], default='IN', max_length=5),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
