# Generated by Django 6.0.5 on 2026-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['total_amount', 'created_at'], name='invoices_in_total_a_15f9f2_idx'),
        ),
    ]
